---
- secret:
    name: SECRET_CONTAINER_IMAGE_OSISM_ANSIBLE
    data:
      DOCKER_PASSWORD: !encrypted/pkcs1-oaep
        - epe/Skvr2KS6NAzaTeGbBhEv6vHkb4+dr2lUkebHEZaC6JVtEMJ0Lps5rjBNdI49qCaLn
          7LQl4iCLKHHpKa9KvPAF35cNq2MKiktecIyrd3j3+3ec4ha5h45bOJf873DATf1BKyozs
          aj6XtkRVPIZgeBCoIukqBlg5GgR+1+927ACI8y3tTT3mWpI92wjPstbL955hw7/GvwRQa
          Zi310M1LRdVFjh+mhMnAwlfxuShOTQi7lGky9yQqZeR0RcyytZCK2/3V+eJHyuJjQ4gl2
          fjYkgPuZm9svTsoCTq8UrFaeuHIxEJocBqymSCR4lDEBYrggMIdnXsxhvRCsyHbkox2Hj
          GoRVc+067d2VB63etuTtVK1HN5G85P3GqzdYfTtja3H3lXMw8cbEbKOWLLNi/BggaRFCz
          TCw4X0ppoJgY+M8nCOgLrdX1nIGB6B0Pdgsn96xTYG6EP1DgAZ4y07FxVQJdS0SSOBy8m
          XRSG8LYEg4Ud2XTE0OuTruxAklI7TG3rbQvdz9S4yMIzl4FFgEgLdZ4OiPNjDMUCUclJx
          IVUkupse11sBNtNBGf7YUu1OOoME9AQnetViR9w0paQJdDzgJRv4SH2fpxo0RlRHvHI1C
          3jYVnSruwapO/WXEsGWlzOWkQEqGhE9UMdVW/JPkjxsvtar6soHOzw7o4E0aRE=
      DOCKER_USERNAME: !encrypted/pkcs1-oaep
        - o6kx9nsGkbWFZRWKdHfYB8hTfKlW87RO6Atd85IEmbRP6v+jSozBcG9Kkt9S7EHsOrZaP
          znDr5wwheGYalh5rj1qYUWjGv+PWis7DEY2a5IA7qgoeIlrZi4QjMfPfUlmkJxrjp3uL7
          3E6+AfpjmDBltSv2BN4KcUvz2ewJoiVXFdUSTQp+i183mgh2QvX+JKFgVHctMxRYiwf9g
          WotCBlt4yrVQzQ3aECL50QDlHEuNAIVOHJ8YXmWtlo4fJAjh9SoQaBCTdS+i/CwKWAGq4
          dPwsNkm4VpNiIR1FQRJT9BuyigGRfpt5Ebde8rhAv8xfH0t+GS7eVlXcdiV7gjdeZBVd8
          1d+yjjEwkLJ+jER5s9YH7SubAliV6S4WhoC+jeiVp7yYFHuIRUNwgIksvXylhoJYHFA6j
          dqh28khue2PQjKkGjWrtJuthS6j+XHR0uvYHOQJuvrhezvF4bH3B2iYVB8qx0i1dITTL+
          QfHFryTwF7ccyAdjsgPjStp12EBibqV0Dpd98Qo21ncXr62hLSLroTomlWEuuQbXLGos0
          A/PCzFOKmwik3v4yEwXNpwxtM+jMuJl2wmC7X5vrashTJye6sv2FqJ1yiXS9P2FWqX6kW
          ZeocUnDo539oxBIBrqLboEXm89ZFyOlHgbXGU0ftrfU/+zuDmCICli1HtQl/Cs=
      DTRACK_API_KEY: !encrypted/pkcs1-oaep
        - qX7CgWo7ApPBRWyo/ovgOzP1Fzdrf37lvRAhvEOOOZTeOGQARtq3PKDoj1wKLIPtDC5nK
          o3oV4HhZ9Wwx22oydP2Djfi4dLIIghawy92P0iZl9OdPqt/2ri+vlJI/UF0wNBLHEwfNk
          DJNLq2Lbx6lGUEWA9wJly3rgtDgSEc9lTfUkkMzTAhusIm0LNtL+UJen983x5hN9nndcB
          v59rcuYh3AXvoChtIWDYKVOZLzvtm1DVCjB7/CXnO7ykQCv/9k15RTybW0r4lDcqKKwgt
          d7OT0dJA7FHdc6g1eJlJPC6eVpGKqQNXlUyvcR2LBhMTXErJ8o/q4Haa0+Q3n4srRwpnV
          WJyjvd1VHV+hQyrG7vPJ0Lk1owr7ENjJ+Kc7olah44xIQoLYuAjd2EsvKwrKdn+XwalcD
          Tbg0pTE5gzjnhjQmYyD1/IDfC2ab3LGRpTf3TqphzweckzLup0uDPFHhMEcz+fH8wWhai
          lDD8xfmFuSOlCiyCFKfOX8GKSVjPYE27vqGrFqDmCEJyqUJwpBnvttB+xQ+dLz/lduMoP
          2JjpukjUD/t1OPgYUcBTMiDOPmJDFltlDo9ZCIBMBkCKeko3CGQCTBTbrwUbVix8lmia6
          2/D7Oef866o9lg1ezwWugKRMGpk0k+XkzADsHHprrw+MLb+NR3VJex9Q/epC2A=

- semaphore:
    name: semaphore-container-image-osism-ansible-push
    max: 1

- job:
    name: container-image-osism-ansible-build
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    vars:
      docker_namespace: osism
      docker_registry: osism.harbor.regio.digital

- job:
    name: abstract-container-image-osism-ansible-push
    abstract: true
    semaphores:
      - name: semaphore-container-image-osism-ansible-push
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    vars:
      docker_namespace: osism
      docker_registry: osism.harbor.regio.digital
      push_image: true
      push_sbom: true

- job:
    name: container-image-osism-ansible-push
    parent: abstract-container-image-osism-ansible-push
    secrets:
      - name: secret
        secret: SECRET_CONTAINER_IMAGE_OSISM_ANSIBLE
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - python-black
        - yamllint
        - container-image-osism-ansible-build
    gate:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - python-black
        - yamllint
    periodic-daily:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - python-black
        - yamllint
    periodic-midnight:
      jobs:
        - container-image-osism-ansible-push
    post:
      jobs:
        - container-image-osism-ansible-push:
            branches: main
    tag:
      jobs:
        - container-image-osism-ansible-push
