---
- name: Build osism-ansible image
  hosts: all

  environment:
    registry: "{{ docker_registry | default('osism.harbor.regio.digital') }}"
    repository: "{{ docker_namespace | default('osism') }}/osism-ansible"
    version: "{{ zuul['tag'] | default('latest') }}"

  tasks:
    - name: Log into registry
      community.docker.docker_login:
        registry_url: "{{ docker_registry }}"
        username: "{{ secret.DOCKER_USERNAME }}"
        password: "{{ secret.DOCKER_PASSWORD }}"
      when: push_image | default(false) | bool
      no_log: true

    - name: Run build script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir | default('.') }}"
        cmd: |
          set -e
          set -o pipefail
          set -x

          # This is a way to use this job also in other repositories
          # (osism/cfg-generics, osism/defaults, ..). The assumption
          # is that if no Containerfile is available, the job was executed
          # from one of the other repositories. There are probably more
          # elegant ways to solve this, but it is good enough for now.
          if [[ ! -e Containerfile ]]; then
              git clone https://github.com/osism/container-image-osism-ansible.git container-image
              pushd container-image
          fi

          created=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          revision=$(git rev-parse --short HEAD)

          if [[ -n $registry ]]; then
              repository="$registry/$repository"
          fi

          docker buildx build \
              --build-arg "VERSION=$version" \
              --label "org.opencontainers.image.created=$created" \
              --label "org.opencontainers.image.documentation=https://osism.github.io" \
              --label "org.opencontainers.image.licenses=ASL 2.0" \
              --label "org.opencontainers.image.revision=$revision" \
              --label "org.opencontainers.image.source=https://github.com/osism/container-image-osism-ansible" \
              --label "org.opencontainers.image.title=osism-ansible" \
              --label "org.opencontainers.image.url=https://www.osism.tech" \
              --label "org.opencontainers.image.vendor=OSISM GmbH" \
              --label "org.opencontainers.image.version=$version" \
              --load \
              --tag "$revision" \
              .  # <-- there is a dot
      changed_when: true

    - name: Run push script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir | default('.') }}"
        cmd: |
          set -e
          set -o pipefail
          set -x

          revision=$(git rev-parse --short HEAD)

          if [[ -n $registry ]]; then
              repository="$registry/$repository"
          fi

          docker tag "$revision" "$repository:$version"
          docker push "$repository:$version"

      when: push_image | default(false) | bool
      changed_when: true
