---
name: Build and push docker image

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build-docker-image.yml
      - Dockerfile
      - files/**
      - patches/**

jobs:

  build-and-push-docker-image:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          scripts/build.sh
          scripts/push.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          REPOSITORY: osism/osism-ansible
