---
name: Check docker syntax

"on":
  push:
    branches:
      - main
    paths:
      - Containerfile
      - .github/workflows/check-docker-syntax.yml
  pull_request:
    paths:
      - Containerfile
      - .github/workflows/check-docker-syntax.yml

jobs:
  check-docker-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: brpaz/hadolint-action@v1.5.0
