---
name: Check docker syntax

on:
  push:
    paths:
      - Dockerfile
      - .github/workflows/syntax-docker.yml
  pull_request:
    paths:
      - Dockerfile
      - .github/workflows/syntax-docker.yml

jobs:
  hadolint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: reviewdog/action-hadolint@v1
        with:
          hadolint_flags: --config .github/hadolint.yml
